### ISSUE TITLE
code issues

### ISSUE THREAD

**Issue by zxyx2023** [JackYFL/DISC#13]
hello，Can you share the code for DIST+DIVIDEMIX?

**Comment by JackYFL** [comment]
Hi, thank you for your interest in our work! This code cannot be found due to some issues. But I can give you some hints on how to modify the DivideMix with DIST. Firstly, you can replace the original GMM with DIST by recording the confidence of each instance. Moreover, you should also modify the dataloader of DivideMix to output an extra index of each instance. The last thing you should notice is to select using DIST at the end of each epoch rather than each iteration. If you have any other questions, please let me know.
