### ISSUE TITLE
Sigma update for high noise rates

### ISSUE THREAD

**Issue by oscaroca** [JackYFL/DISC#7]
Hi Jack,

In the appendix of the paper, you talk about using (in cifar10 and cifar100) a 0.3 sigma for lower noise rates and a 0.5 sigma for high noise rates, such as 0.6 instance noise. However, I couldn't find where you change it in the code. In the DISC class, we can find the sigma fixed at 0.5, but I think it doesn't change like the momentum or the lambda for the hard sample does for the noise level we are using.

**Comment by JackYFL** [comment]
Hi, thank you for your interest to our work! I think it’s an error when we clean up the code. It should be 0.3 for the low label noise. Moreover, I agree with you that the influence of momentum and lambda is larger than sigma, since the momentum for correction is large enough which could not correct more instances to improve the performance. Also, I think label correction is a challenging problem due to the confirmation bias caused by model itself.
